name: java-development-devcontainer
services:
  management:
    container_name: java-development
    image: mcr.microsoft.com/devcontainers/base:bookworm
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres
      POSTGRES_HOSTNAME: postgresdb
    volumes:
      - ../:/workspaces:cached
    command: sleep infinity
    network_mode: service:database
  database:
    container_name: postgresdb
    image: postgres:16-alpine
    restart: unless-stopped
    volumes:
      - postgres:/var/lib/postgresql/data
    environment:
      POSTGRES_PASSWORD: postgres
      POSTGRES_USER: postgres
      POSTGRES_DB: postgres

volumes:
  postgres:
